CREATE DATABASE OLTP_RETAIL;
USE DATABASE OLTP_RETAIL;
CREATE OR REPLACE SCHEMA SRC;


CREATE DATABASE OLAP_RETAIL;
USE DATABASE OLAP_RETAIL;
CREATE OR REPLACE SCHEMA DWH_STG
CREATE OR REPLACE SCHEMA DWH_LND
CREATE OR REPLACE SCHEMA DWH_TMP
CREATE OR REPLACE SCHEMA DWH_TGT