CREATE OR REPLACE TABLE OLAP_RETAIL.DWH_LND.COUNTRY
(
    ID INT,
    COUNTRY_DESC VARCHAR(512)
);
CREATE OR REPLACE TABLE OLAP_RETAIL.DWH_TMP.COUNTRY
(
    ID INT,
    COUNTRY_DESC VARCHAR(512)
);
create or replace TABLE OLAP_RETAIL.DWH_TGT.COUNTRY (
	ID NUMBER(38,0),
	COUNTRY_KEY NUMBER(38,0),
	COUNTRY_DESC VARCHAR(512),
	EFFECTIVE_START_DT DATE,
	EFFECTIVE_END_DT DATE,
	ACTIVE_STATUS BOOLEAN,
	REC_INS_TS TIMESTAMP_NTZ(9),
	REC_UPD_TS TIMESTAMP_NTZ(9)
);