#DATE TIME FORMAT
TIMESTAMP_FORMAT = '%Y%m%d%H%M%S'

#FILE EXTENSION
CSV_EXTENSION = '.csv'

#SOURCE CONSTANTS
SOURCE_DB = 'OLTP_RETAIL'
SRC_SCHEMA = 'SRC'

#DATAWAREHOUSE CONSTANTS
TARGET_DB = 'OLAP_RETAIL'
STG_SCHEMA = 'DWH_STG'
LND_SCHEMA = 'DWH_LND'
TMP_SCHEMA = 'DWH_TMP'
TGT_SCHEMA = 'DWH_TGT'
INTERNAL_STAGE = 'INTERNAL_STAGE'
CSV_FILE_FORMAT = 'CSV_FORMAT'